/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import java.net.MalformedURLException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static uas.Barang.*;
import static uas.Penjualan.*;
import static uas.DatabaseUtil.*;

/**
 *
 * @author user
 */
public class Form extends javax.swing.JFrame {
    DefaultTableModel modelBarang = new DefaultTableModel();
    DefaultTableModel modelJual = new DefaultTableModel();
    String dest = "C:\\Users\\user\\Downloads\\Cetak Data Penjualan-UAS PBO2.pdf";
    /**
     * Creates new form FormBarang
     */
    public Form() {
        initComponents();
        initTableBarang();
        initTableJual();
        CheckConnection();
        showDataModelBarang();
        showDataModelJual();
        CloseConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabBarang = new javax.swing.JTabbedPane();
        panelBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputKodeBarang = new javax.swing.JTextField();
        inputNmBarang = new javax.swing.JTextField();
        inputHargaBarang = new javax.swing.JTextField();
        btnTambahBarang = new javax.swing.JButton();
        btnHapusBarang = new javax.swing.JButton();
        btnUpdateBarang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        btnTutupBarang = new javax.swing.JButton();
        panelPenjualan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inputKodeBarangJual = new javax.swing.JTextField();
        inputNamaBarangJual = new javax.swing.JTextField();
        inputHargaJual = new javax.swing.JTextField();
        inputJumlah = new javax.swing.JTextField();
        inputTotalBayar = new javax.swing.JTextField();
        btnHapusJual = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePenjualan = new javax.swing.JTable();
        btnTutupJual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Gudang Barang");
        setName("FormBarang"); // NOI18N

        panelBarang.setPreferredSize(new java.awt.Dimension(555, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Master Barang");

        jLabel3.setText("Kode");

        jLabel4.setText("Nama");

        jLabel5.setText("Harga");

        inputKodeBarang.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                inputKodeBarangCaretUpdate(evt);
            }
        });

        btnTambahBarang.setText("Tambah");
        btnTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBarangActionPerformed(evt);
            }
        });

        btnHapusBarang.setText("Hapus");
        btnHapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusBarangActionPerformed(evt);
            }
        });

        btnUpdateBarang.setText("Update");
        btnUpdateBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBarangActionPerformed(evt);
            }
        });

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);

        btnTutupBarang.setText("Tutup");
        btnTutupBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBarangLayout = new javax.swing.GroupLayout(panelBarang);
        panelBarang.setLayout(panelBarangLayout);
        panelBarangLayout.setHorizontalGroup(
            panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarangLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTutupBarang)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarangLayout.createSequentialGroup()
                        .addComponent(btnTambahBarang)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateBarang)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusBarang)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(204, 204, 204))))
            .addGroup(panelBarangLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputKodeBarang)
                    .addComponent(inputNmBarang)
                    .addComponent(inputHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarangLayout.setVerticalGroup(
            panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputNmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahBarang)
                    .addComponent(btnHapusBarang)
                    .addComponent(btnUpdateBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTutupBarang)
                .addContainerGap())
        );

        tabBarang.addTab("Barang", panelBarang);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Form Penjualan");

        jLabel6.setText("Kode Barang");

        jLabel7.setText("Nama Barang");

        jLabel8.setText("Harga Satuan");

        jLabel9.setText("Jumlah");

        jLabel10.setText("Total Bayar");

        inputKodeBarangJual.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                inputKodeBarangJualCaretUpdate(evt);
            }
        });

        inputNamaBarangJual.setEditable(false);

        inputHargaJual.setEditable(false);
        inputHargaJual.setText("0");

        inputJumlah.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                inputJumlahCaretUpdate(evt);
            }
        });
        inputJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJumlahActionPerformed(evt);
            }
        });

        inputTotalBayar.setEditable(false);
        inputTotalBayar.setText("0");

        btnHapusJual.setText("Hapus");
        btnHapusJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusJualActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        tablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenjualanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePenjualan);

        btnTutupJual.setText("Tutup");
        btnTutupJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupJualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPenjualanLayout = new javax.swing.GroupLayout(panelPenjualan);
        panelPenjualan.setLayout(panelPenjualanLayout);
        panelPenjualanLayout.setHorizontalGroup(
            panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPenjualanLayout.createSequentialGroup()
                        .addGap(0, 474, Short.MAX_VALUE)
                        .addComponent(btnTutupJual)))
                .addContainerGap())
            .addGroup(panelPenjualanLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPenjualanLayout.createSequentialGroup()
                            .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel6))
                            .addGap(3, 3, 3)))
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inputJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputHargaJual, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNamaBarangJual, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputKodeBarangJual, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPenjualanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPenjualanLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPenjualanLayout.createSequentialGroup()
                        .addComponent(btnHapusJual)
                        .addGap(18, 18, 18)
                        .addComponent(btnCetak)
                        .addGap(166, 166, 166))))
        );
        panelPenjualanLayout.setVerticalGroup(
            panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputKodeBarangJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputNamaBarangJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inputTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusJual)
                    .addComponent(btnCetak))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTutupJual)
                .addContainerGap())
        );

        tabBarang.addTab("Penjualan", panelPenjualan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabBarang)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBarangActionPerformed
        // TODO add your handling code here:
        CheckConnection();
        String kode = inputKodeBarang.getText();
        String nama = inputNmBarang.getText();
        String harga = inputHargaBarang.getText();
        Barang dataBarang = new Barang(kode, nama, harga);
        Barang.insertDataBarang(dataBarang);
        showDataModelBarang();
        CloseConnection();
        clearInputBarang();
    }//GEN-LAST:event_btnTambahBarangActionPerformed

    private void btnTutupJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupJualActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnTutupJualActionPerformed

    private void btnTutupBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupBarangActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnTutupBarangActionPerformed

    private void tableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseClicked
        // TODO add your handling code here:
        int baris = tableBarang.getSelectedRow();
        String kolom1 = tableBarang.getValueAt(baris,0).toString();
        String kolom2 = tableBarang.getValueAt(baris, 1).toString();
        String kolom3 = tableBarang.getValueAt(baris, 2).toString();
        inputKodeBarang.setText(kolom1);
        inputNmBarang.setText(kolom2);
        inputHargaBarang.setText(kolom3);
    }//GEN-LAST:event_tableBarangMouseClicked

    private void inputKodeBarangCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_inputKodeBarangCaretUpdate
        // TODO add your handling code here:
        try {
            CheckConnection();
            String kode = inputKodeBarang.getText();
            ResultSet result_data = getDataBarangByKode(kode);
            while(result_data.next()) {
                inputNmBarang.setText(result_data.getString("nama"));
                inputHargaBarang.setText(result_data.getString("harga"));
            }
            CloseConnection();
        } catch(SQLException e) {
            System.out.println("Error tampil data by kode: "+e.getMessage());
        }
    }//GEN-LAST:event_inputKodeBarangCaretUpdate

    private void btnHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusBarangActionPerformed
        // TODO add your handling code here:
        CheckConnection();
        String kode = inputKodeBarang.getText();
        deleteDataBarang(kode);
        showDataModelBarang();
        CloseConnection();
        clearInputBarang();
    }//GEN-LAST:event_btnHapusBarangActionPerformed

    private void btnUpdateBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBarangActionPerformed
        // TODO add your handling code here:
        String kode = inputKodeBarang.getText();
        String harga = inputHargaBarang.getText();
        String nama = inputNmBarang.getText();
        CheckConnection();
        Barang dataBarang = new Barang(kode, nama, harga);
        updateDataBarang(kode, dataBarang);
        showDataModelBarang();
        CloseConnection();
        clearInputBarang();
    }//GEN-LAST:event_btnUpdateBarangActionPerformed

    private void inputKodeBarangJualCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_inputKodeBarangJualCaretUpdate
        // TODO add your handling code here:
        try {
            CheckConnection();
            String kodeBarang = inputKodeBarangJual.getText();
            ResultSet result_data = getDataBarangByKode(kodeBarang);
            while(result_data.next()) {
            inputNamaBarangJual.setText(result_data.getString("nama"));
            inputHargaJual.setText(result_data.getString("harga"));
            }
            CloseConnection();
        } catch (SQLException e) {
            System.out.println("Error tampil data jual by kode: "+e.getMessage());
        }
    }//GEN-LAST:event_inputKodeBarangJualCaretUpdate

    private void inputJumlahCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_inputJumlahCaretUpdate
        // TODO add your handling code here:
        if(!inputJumlah.getText().isEmpty()) {
            int harga = Integer.parseInt(inputHargaJual.getText());
            int jumlah = Integer.parseInt(inputJumlah.getText());
            String total = String.valueOf(harga*jumlah);
            inputTotalBayar.setText(total);
        }
    }//GEN-LAST:event_inputJumlahCaretUpdate

    private void tablePenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenjualanMouseClicked
        // TODO add your handling code here:
        int baris = tablePenjualan.getSelectedRow();
        String kolom2 = tablePenjualan.getValueAt(baris, 1).toString();
        String kolom3 = tablePenjualan.getValueAt(baris, 2).toString();
        String kolom4 = tablePenjualan.getValueAt(baris, 3).toString();
        
        inputKodeBarangJual.setText(kolom2);
        inputJumlah.setText(kolom4);
    }//GEN-LAST:event_tablePenjualanMouseClicked

    private void inputJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJumlahActionPerformed
        // TODO add your handling code here:
        String kode_barang = inputKodeBarangJual.getText();
        String jumlah = inputJumlah.getText();
        String total = inputTotalBayar.getText();
        SimpleDateFormat formatedDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = new Date(System.currentTimeMillis());
        String tanggal = formatedDate.format(date);
        Penjualan dataJual = new Penjualan(kode_barang, jumlah, total, tanggal);
        CheckConnection();
        inputDataJual(dataJual);
        showDataModelJual();
        CloseConnection();
        clearInputJual();
    }//GEN-LAST:event_inputJumlahActionPerformed

    private void btnHapusJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusJualActionPerformed
        // TODO add your handling code here:
        int baris = tablePenjualan.getSelectedRow();
        String idJual = tablePenjualan.getValueAt(baris, 0).toString();
        CheckConnection();
        deleteDataJual(idJual);
        showDataModelJual();
        CloseConnection();
        clearInputJual();
    }//GEN-LAST:event_btnHapusJualActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        try {
            CheckConnection();
            cetakDataJualPdf(dest);
            CloseConnection();
        } catch (MalformedURLException ex) {
            System.out.println("Error cetak data: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapusBarang;
    private javax.swing.JButton btnHapusJual;
    private javax.swing.JButton btnTambahBarang;
    private javax.swing.JButton btnTutupBarang;
    private javax.swing.JButton btnTutupJual;
    private javax.swing.JButton btnUpdateBarang;
    private javax.swing.JTextField inputHargaBarang;
    private javax.swing.JTextField inputHargaJual;
    private javax.swing.JTextField inputJumlah;
    private javax.swing.JTextField inputKodeBarang;
    private javax.swing.JTextField inputKodeBarangJual;
    private javax.swing.JTextField inputNamaBarangJual;
    private javax.swing.JTextField inputNmBarang;
    private javax.swing.JTextField inputTotalBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelBarang;
    private javax.swing.JPanel panelPenjualan;
    private javax.swing.JTabbedPane tabBarang;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTable tablePenjualan;
    // End of variables declaration//GEN-END:variables
    
    private void initTableBarang() {
        tableBarang.setModel(modelBarang);
        modelBarang.addColumn("Kode");
        modelBarang.addColumn("Nama Barang");
        modelBarang.addColumn("Harga");
    }
    
    private void initTableJual() {
        tablePenjualan.setModel(modelJual);
        modelJual.addColumn("ID");
        modelJual.addColumn("Kode");
        modelJual.addColumn("Nama");
        modelJual.addColumn("Jumlah");
        modelJual.addColumn("Total Bayar");
        modelJual.addColumn("Tanggal");
    }
    
    private void clearInputBarang() {
        inputKodeBarang.setText("");
        inputNmBarang.setText("");
        inputHargaBarang.setText("");
    }
    
    private void clearInputJual() {
        inputKodeBarangJual.setText("");
        inputNamaBarangJual.setText("");
        inputHargaJual.setText("0");
        inputJumlah.setText("");
        inputTotalBayar.setText("0");
    }
    
    private void showDataModelBarang() {
        showDataBarang(modelBarang);
    }
    
    private void showDataModelJual() {
        showDataJual(modelJual);
    }
}
